name: DP2Plugin
version: '1.0-SNAPSHOT'
main: com.febrie.dpp.SimpleRPGMain
api-version: '1.21'
authors: [ Febrie, CoffeeTory ]
description: SimpleRPG 기능을 위한 통합 플러그인
website: https://github.com/Febriez/MyPage

commands:
  teamselect:
    description: "팀을 선택합니다"
    usage: "/teamselect <red|blue|green|yellow>"
  startcore:
    description: "코어전을 시작합니다"
    usage: "/startcore"
    permission: simplerp.admin
  skills:
    description: "보유 스킬을 확인합니다"
    usage: "/skills"
  skillinfo:
    description: "스킬 정보를 확인합니다"
    usage: "/skillinfo <skillname>"
  admin:
    description: "관리자 명령어"
    usage: "/admin <reload>"
    permission: simplerp.admin

permissions:
  simplerp.admin:
    description: "관리자 권한"
    default: op
