name: DP2Plugin
version: '1.0-SNAPSHOT'
main: com.febrie.dpp.SimpleRPGMain
api-version: '1.21'
authors: [ Febrie, CoffeeTory ]
description: SimpleRPG 기능을 위한 통합 플러그인
website: https://github.com/Febriez/MyPage

commands:
  팀선택:
    description: "팀을 선택합니다"
    usage: "/팀선택 <빨강|파랑|초록|노랑>"
    aliases: [teamselect, 팀]
  코어전시작:
    description: "코어전을 시작합니다"
    usage: "/코어전시작"
    permission: simplerp.admin
    aliases: [startcore, 코어전]
  스킬목록:
    description: "보유 스킬을 확인합니다"
    usage: "/스킬목록"
    aliases: [skills, 스킬]
  스킬정보:
    description: "스킬 정보를 확인합니다"
    usage: "/스킬정보 <스킬이름>"
    aliases: [skillinfo]
  관리자:
    description: "관리자 명령어"
    usage: "/관리자 <리로드|상점등록>"
    permission: simplerp.admin
    aliases: [admin]

permissions:
  simplerp.admin:
    description: "관리자 권한"
    default: op
